from __future__ import annotations

import pytest


@pytest.mark.skip(
    reason=(
        "Pending fixture extraction from "
        "Reference_docs/goal_based_allocation_model_latest.xlsx. "
        "Will be unblocked once Testing/golden_fixtures/workbook_baseline.json exists."
    )
)
def test_workbook_baseline_within_one_rupee():
    """Row-by-row assertion that the engine matches the workbook within ₹1
    on cols K, M, N, P, AC, AP. Loaded from a JSON fixture generated by
    a small dev-only `extract_workbook_fixture.py` script."""
    pass
