"""add risk_capacity, investment_experience, liquidity_needs, income_needs

Revision ID: b8b16d9c1ccf
Revises: 998b6998b6aa
Create Date: 2026-03-21 11:38:00.854219
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b8b16d9c1ccf'
down_revision: Union[str, None] = '998b6998b6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
