-- Value Research mirror. Generated by app/domains/vr_data/schema.py:create_schema_sql().
-- Regenerate:  python -m scripts.vr_bootstrap --print-sql
-- Reverses completely with:  DROP SCHEMA vr CASCADE;

CREATE SCHEMA IF NOT EXISTS vr;

CREATE TABLE IF NOT EXISTS vr.sync_state (
	table_name VARCHAR(64) NOT NULL, 
	watermark VARCHAR(32), 
	last_run_at TIMESTAMP WITH TIME ZONE, 
	last_success_at TIMESTAMP WITH TIME ZONE, 
	last_status VARCHAR(16), 
	last_error TEXT, 
	last_row_count INTEGER, 
	total_rows INTEGER, 
	last_page_count INTEGER, 
	PRIMARY KEY (table_name)
);

CREATE TABLE IF NOT EXISTS vr.bulk_budget (
	table_name VARCHAR(64) NOT NULL, 
	budget_date DATE NOT NULL, 
	requests_used INTEGER DEFAULT '0' NOT NULL, 
	last_request_at TIMESTAMP WITH TIME ZONE, 
	last_download_url TEXT, 
	PRIMARY KEY (table_name, budget_date)
);

CREATE TABLE IF NOT EXISTS vr.scheme_link (
	plan_id TEXT NOT NULL, 
	scheme_code VARCHAR(20), 
	isin VARCHAR(20), 
	amfi_code TEXT, 
	match_method VARCHAR(24), 
	confidence NUMERIC, 
	linked_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (plan_id)
);
CREATE INDEX IF NOT EXISTS ix_vr_scheme_link_scheme_code ON vr.scheme_link (scheme_code);
CREATE INDEX IF NOT EXISTS ix_vr_scheme_link_isin ON vr.scheme_link (isin);

CREATE TABLE IF NOT EXISTS vr.fund_basic_details (
	plan_id TEXT, 
	basic_name TEXT, 
	short_name TEXT, 
	plan_name TEXT, 
	basic_short_name TEXT, 
	scheme_name TEXT, 
	fund_name TEXT, 
	fund_id TEXT, 
	face_value NUMERIC, 
	redemption_note TEXT, 
	equity_max NUMERIC, 
	equity_min NUMERIC, 
	debt_max NUMERIC, 
	debt_min NUMERIC, 
	money_mkt_max NUMERIC, 
	money_mkt_min NUMERIC, 
	comm_min NUMERIC, 
	comm_max NUMERIC, 
	equity_derivatives_min NUMERIC, 
	equity_derivatives_max NUMERIC, 
	reit_invit_min NUMERIC, 
	reit_invit_max NUMERIC, 
	issue_open DATE, 
	issue_stated_close DATE, 
	issue_actual_close DATE, 
	allottment_date DATE, 
	late_redemption DATE, 
	resale_start_date DATE, 
	transfer_agent TEXT, 
	transfer_agent_short_name TEXT, 
	transfer_agent_email TEXT, 
	objective_text TEXT, 
	amfi_code TEXT, 
	nsdl_code TEXT, 
	is_dividend TEXT, 
	auditor_code TEXT, 
	custodian_code TEXT, 
	is_direct_plan TEXT, 
	reg_plan_id TEXT, 
	status TEXT, 
	dividend_periodicity TEXT, 
	is_etf_fund TEXT, 
	lock_in TEXT, 
	lock_in_period_days INTEGER, 
	variant TEXT, 
	variant_fund_id TEXT, 
	is_rgess_plan TEXT, 
	stated_annual_expense NUMERIC, 
	is_fof TEXT, 
	last_etf_trade_date DATE, 
	is_index_fund TEXT, 
	interest_risk_name TEXT, 
	credit_risk_name TEXT, 
	potential_risk_class TEXT, 
	is_retirement_fund TEXT, 
	is_interval_fund TEXT, 
	fund_objective_description TEXT, 
	instant_redemption_facility TEXT, 
	riskometer_id TEXT, 
	riskometer_details JSONB, 
	amc_id TEXT, 
	amc_details JSONB, 
	vr_category_id TEXT, 
	vr_category_name TEXT, 
	vr_primary_category_id TEXT, 
	vr_primary_category_name TEXT, 
	sebi_category_id TEXT, 
	sebi_category_name TEXT, 
	sebi_primary_category_id TEXT, 
	sebi_primary_category_name TEXT, 
	type_id TEXT, 
	type_name TEXT, 
	benchmark_details JSONB, 
	fund_manager_details JSONB, 
	load_note TEXT, 
	fund_load_cdsc_details JSONB, 
	latest_expense_ratio NUMERIC, 
	latest_turnover_ratio NUMERIC, 
	latest_aum NUMERIC, 
	sebi_sub_category_id TEXT, 
	sebi_sub_category_name TEXT, 
	amc_aum TEXT, 
	plan_type TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_fund_basic_details PRIMARY KEY (plan_id)
);
CREATE INDEX IF NOT EXISTS ix_vr_fund_basic_details_sebi_category_id ON vr.fund_basic_details (sebi_category_id);
CREATE INDEX IF NOT EXISTS ix_vr_fund_basic_details_amfi_code ON vr.fund_basic_details (amfi_code);
CREATE INDEX IF NOT EXISTS ix_vr_fund_basic_details_status ON vr.fund_basic_details (status);

CREATE TABLE IF NOT EXISTS vr.subplan_isin (
	isin_code TEXT, 
	plan_id TEXT, 
	subplan_code TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_subplan_isin PRIMARY KEY (plan_id, subplan_code, isin_code)
);
CREATE INDEX IF NOT EXISTS ix_vr_subplan_isin_isin_code ON vr.subplan_isin (isin_code);

CREATE TABLE IF NOT EXISTS vr.fund_sip_returns (
	plan_id TEXT, 
	as_on_date DATE, 
	r10year NUMERIC, 
	r10year_value NUMERIC, 
	r15year NUMERIC, 
	r15year_value NUMERIC, 
	r1year NUMERIC, 
	r1year_value NUMERIC, 
	r20year NUMERIC, 
	r20year_value NUMERIC, 
	r2year NUMERIC, 
	r2year_value NUMERIC, 
	r3month NUMERIC, 
	r3month_value NUMERIC, 
	r3year NUMERIC, 
	r3year_value NUMERIC, 
	r4year NUMERIC, 
	r4year_value NUMERIC, 
	r5year NUMERIC, 
	r5year_value NUMERIC, 
	r6month NUMERIC, 
	r6month_value NUMERIC, 
	r9month NUMERIC, 
	r9month_value NUMERIC, 
	rsinceinception TEXT, 
	rsinceinception_value NUMERIC, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_fund_sip_returns PRIMARY KEY (plan_id, as_on_date)
);
CREATE INDEX IF NOT EXISTS ix_vr_fund_sip_returns_as_on_date ON vr.fund_sip_returns (as_on_date);

CREATE TABLE IF NOT EXISTS vr.fund_performance_details (
	plan_id TEXT, 
	nav_date DATE, 
	nav NUMERIC, 
	sip_returns JSONB, 
	stats_variables JSONB, 
	trailing_returns JSONB, 
	adjusted_nav NUMERIC, 
	high_52_week TEXT, 
	low_52_week TEXT, 
	latest_dividend_date TEXT, 
	latest_dividend TEXT, 
	fund_id TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_fund_performance_details PRIMARY KEY (plan_id, nav_date)
);
CREATE INDEX IF NOT EXISTS ix_vr_fund_performance_details_nav_date ON vr.fund_performance_details (nav_date);

CREATE TABLE IF NOT EXISTS vr.fund_holdings_details (
	plan_id TEXT, 
	as_on_date DATE, 
	plan_short_name TEXT, 
	plan_basic_name TEXT, 
	security_id TEXT, 
	security_name TEXT, 
	asset_id TEXT, 
	asset_description TEXT, 
	asset_value NUMERIC, 
	num_of_shares NUMERIC, 
	asset_percentage NUMERIC, 
	coupon_rate NUMERIC, 
	maturity DATE, 
	rating_id TEXT, 
	rating_name TEXT, 
	sebi_cap_rank TEXT, 
	asset_class TEXT, 
	asset_isin TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_fund_holdings_details PRIMARY KEY (plan_id, as_on_date, security_id)
);
CREATE INDEX IF NOT EXISTS ix_vr_fund_holdings_details_asset_isin ON vr.fund_holdings_details (asset_isin);
CREATE INDEX IF NOT EXISTS ix_vr_fund_holdings_details_security_id ON vr.fund_holdings_details (security_id);
CREATE INDEX IF NOT EXISTS ix_vr_fund_holdings_details_as_on_date ON vr.fund_holdings_details (as_on_date);
CREATE INDEX IF NOT EXISTS ix_vr_fund_holdings_details_plan_id ON vr.fund_holdings_details (plan_id);

CREATE TABLE IF NOT EXISTS vr.fund_holdings_aggregate_equity (
	plan_id TEXT, 
	as_on_date DATE, 
	sector_details JSONB, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_fund_holdings_aggregate_equity PRIMARY KEY (plan_id, as_on_date)
);

CREATE TABLE IF NOT EXISTS vr.fund_holdings_aggregate_debt (
	plan_id TEXT, 
	as_on_date DATE, 
	holdings_debtstated JSONB, 
	holdings_maturity JSONB, 
	holdings_rating JSONB, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_fund_holdings_aggregate_debt PRIMARY KEY (plan_id, as_on_date)
);

CREATE TABLE IF NOT EXISTS vr.fund_transaction_details (
	plan_id TEXT, 
	subplan_id TEXT, 
	plan_name TEXT, 
	full_name TEXT, 
	isin_code TEXT, 
	plan_type TEXT, 
	rta_code TEXT, 
	rta_name TEXT, 
	fund_amc_id TEXT, 
	fund_scheme_id TEXT, 
	scm_pur_available TEXT, 
	scm_red_available TEXT, 
	scm_sip_available TEXT, 
	scm_switch_in_available TEXT, 
	scm_switch_out_available TEXT, 
	scm_swp_available TEXT, 
	scm_stp_available TEXT, 
	latest_sip_details JSONB, 
	sip_stp_swp_min_amounts JSONB, 
	sip_swp_stp_details JSONB, 
	min_initial_investment NUMERIC, 
	min_subsequent_investment NUMERIC, 
	min_withdrawl_amount NUMERIC, 
	min_subsequent_sip_investment NUMERIC, 
	min_swp_widw NUMERIC, 
	min_balance NUMERIC, 
	min_widw_unit NUMERIC, 
	min_subsequent_investment_unit NUMERIC, 
	min_investment_multiples TEXT, 
	transaction_status TEXT, 
	max_inv_amount NUMERIC, 
	min_withdrawal_multiple_amount NUMERIC, 
	minor_investments_allowed TEXT, 
	fund_id TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_fund_transaction_details PRIMARY KEY (plan_id, subplan_id)
);
CREATE INDEX IF NOT EXISTS ix_vr_fund_transaction_details_transaction_status ON vr.fund_transaction_details (transaction_status);
CREATE INDEX IF NOT EXISTS ix_vr_fund_transaction_details_isin_code ON vr.fund_transaction_details (isin_code);
CREATE INDEX IF NOT EXISTS ix_vr_fund_transaction_details_rta_code ON vr.fund_transaction_details (rta_code);

CREATE TABLE IF NOT EXISTS vr.nav (
	plan_id TEXT, 
	adjusted_nav NUMERIC, 
	nav NUMERIC, 
	nav_date DATE, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_nav PRIMARY KEY (plan_id, nav_date)
);
CREATE INDEX IF NOT EXISTS ix_vr_nav_nav_date ON vr.nav (nav_date);

CREATE TABLE IF NOT EXISTS vr.fund_returns_annual (
	plan_id TEXT, 
	returns NUMERIC, 
	year INTEGER, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_fund_returns_annual PRIMARY KEY (plan_id, year)
);
CREATE INDEX IF NOT EXISTS ix_vr_fund_returns_annual_year ON vr.fund_returns_annual (year);

CREATE TABLE IF NOT EXISTS vr.fund_dividends (
	plan_id TEXT, 
	corp_div_in_rs NUMERIC, 
	corp_dividend NUMERIC, 
	div_date DATE, 
	is_tax_adjustable TEXT, 
	percentage NUMERIC, 
	percentage_rs_per_unit NUMERIC, 
	record_date DATE, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_fund_dividends PRIMARY KEY (plan_id, div_date, record_date)
);
CREATE INDEX IF NOT EXISTS ix_vr_fund_dividends_div_date ON vr.fund_dividends (div_date);

CREATE TABLE IF NOT EXISTS vr.deleted_logs (
	log_id TEXT, 
	table_name TEXT, 
	key1 TEXT, 
	value1 TEXT, 
	key2 TEXT, 
	value2 TEXT, 
	key3 TEXT, 
	value3 TEXT, 
	key4 TEXT, 
	value4 TEXT, 
	key5 TEXT, 
	value5 TEXT, 
	key6 TEXT, 
	value6 TEXT, 
	key7 TEXT, 
	value7 TEXT, 
	key8 TEXT, 
	value8 TEXT, 
	key9 TEXT, 
	value9 TEXT, 
	key10 TEXT, 
	value10 TEXT, 
	deleted_ts TIMESTAMP WITH TIME ZONE, 
	modified_ts TIMESTAMP WITH TIME ZONE, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_deleted_logs PRIMARY KEY (log_id)
);
CREATE INDEX IF NOT EXISTS ix_vr_deleted_logs_table_name ON vr.deleted_logs (table_name);
CREATE INDEX IF NOT EXISTS ix_vr_deleted_logs_deleted_ts ON vr.deleted_logs (deleted_ts);

CREATE TABLE IF NOT EXISTS vr.subplans (
	plan_id TEXT, 
	subplan_full_name TEXT, 
	subplan_id TEXT, 
	subplan_name TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_subplans PRIMARY KEY (plan_id, subplan_id)
);

CREATE TABLE IF NOT EXISTS vr.fund_status (
	status_description TEXT, 
	status_id TEXT, 
	status_detail TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_fund_status PRIMARY KEY (status_id)
);

CREATE TABLE IF NOT EXISTS vr.sebi_categories (
	category_name TEXT, 
	primary_category_id TEXT, 
	primary_category_name TEXT, 
	sebi_category_id TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_sebi_categories PRIMARY KEY (sebi_category_id)
);

CREATE TABLE IF NOT EXISTS vr.fund_categories (
	category_id TEXT, 
	primary_category_id TEXT, 
	category_name TEXT, 
	is_active TEXT, 
	primary_category_name TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_fund_categories PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS vr.rta_codes (
	plan_id TEXT, 
	as_on_date DATE, 
	fund_amc_id TEXT, 
	fund_scheme_id TEXT, 
	rta_code TEXT, 
	rta_name TEXT, 
	subplan_id TEXT, 
	subplan_name TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_rta_codes PRIMARY KEY (plan_id, subplan_id)
);
CREATE INDEX IF NOT EXISTS ix_vr_rta_codes_rta_code ON vr.rta_codes (rta_code);

CREATE TABLE IF NOT EXISTS vr.securities (
	security_id TEXT, 
	security_type_code TEXT, 
	base_currency_iso_code TEXT, 
	instrument_description TEXT, 
	isin TEXT, 
	isin_as_of_date DATE, 
	full_name TEXT, 
	short_name TEXT, 
	name_as_of_date DATE, 
	series TEXT, 
	coupon_rate NUMERIC, 
	maturity_id TEXT, 
	maturity DATE, 
	asset_class TEXT, 
	description TEXT, 
	entity_id TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_securities PRIMARY KEY (security_id)
);
CREATE INDEX IF NOT EXISTS ix_vr_securities_isin ON vr.securities (isin);
CREATE INDEX IF NOT EXISTS ix_vr_securities_entity_id ON vr.securities (entity_id);

CREATE TABLE IF NOT EXISTS vr.credit_rating_score (
	rating TEXT, 
	rating_id TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_credit_rating_score PRIMARY KEY (rating_id)
);

CREATE TABLE IF NOT EXISTS vr.instrument (
	abv TEXT, 
	asset_class TEXT, 
	asset_id TEXT, 
	description TEXT, 
	instrument_type_id TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_instrument PRIMARY KEY (asset_id)
);

CREATE TABLE IF NOT EXISTS vr.countries (
	short_name TEXT, 
	full_name TEXT, 
	iso_country_code TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_countries PRIMARY KEY (iso_country_code)
);

CREATE TABLE IF NOT EXISTS vr.fund_plans (
	plan_id TEXT, 
	allottment_date DATE, 
	amfi_code TEXT, 
	basic_name TEXT, 
	basic_short_name TEXT, 
	comm_max NUMERIC, 
	comm_min NUMERIC, 
	credit_risk_name TEXT, 
	debt_max NUMERIC, 
	debt_min NUMERIC, 
	dividend_periodicity TEXT, 
	equity_derivatives_max NUMERIC, 
	equity_derivatives_min NUMERIC, 
	equity_max NUMERIC, 
	equity_min NUMERIC, 
	face_value NUMERIC, 
	fund_name TEXT, 
	fund_objective_description TEXT, 
	interest_risk_name TEXT, 
	is_direct_plan TEXT, 
	is_dividend TEXT, 
	is_etf_fund TEXT, 
	is_fof TEXT, 
	is_index_fund TEXT, 
	is_interval_fund TEXT, 
	is_retirement_fund TEXT, 
	is_rgess_plan TEXT, 
	isin_code TEXT, 
	issue_actual_close DATE, 
	issue_open DATE, 
	issue_stated_close DATE, 
	last_etf_trade_date DATE, 
	late_redemption DATE, 
	lock_in TEXT, 
	lock_in_period_days INTEGER, 
	max_inv_amount NUMERIC, 
	min_balance NUMERIC, 
	min_initial_investment NUMERIC, 
	min_investment_multiples TEXT, 
	min_subsequent_investment NUMERIC, 
	min_subsequent_investment_unit NUMERIC, 
	min_widw_unit NUMERIC, 
	min_withdrawal_multiple_amount NUMERIC, 
	min_withdrawl_amount NUMERIC, 
	minor_investments_allowed TEXT, 
	money_mkt_max NUMERIC, 
	money_mkt_min NUMERIC, 
	new_fund TEXT, 
	objective_text TEXT, 
	plan_name TEXT, 
	potential_risk_class TEXT, 
	redemption_note TEXT, 
	reit_invit_max NUMERIC, 
	reit_invit_min NUMERIC, 
	resale_start_date DATE, 
	rta_code TEXT, 
	scheme_name TEXT, 
	short_name TEXT, 
	stated_annual_expense NUMERIC, 
	status TEXT, 
	transaction_status TEXT, 
	amc_id TEXT, 
	category_id TEXT, 
	type_id TEXT, 
	sip TEXT, 
	sip_note TEXT, 
	swp TEXT, 
	min_swp_widw NUMERIC, 
	stp TEXT, 
	min_subsequent_sip_investment NUMERIC, 
	transfer_agent TEXT, 
	transfer_agent_short_name TEXT, 
	transfer_agent_email TEXT, 
	benchmark TEXT, 
	colour TEXT, 
	auditor_code TEXT, 
	custodian_code TEXT, 
	reg_plan_id TEXT, 
	variant TEXT, 
	variant_fund_id TEXT, 
	fund_id TEXT, 
	instant_redemption_facility TEXT, 
	nsdl_code TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_fund_plans PRIMARY KEY (plan_id)
);
CREATE INDEX IF NOT EXISTS ix_vr_fund_plans_amfi_code ON vr.fund_plans (amfi_code);
CREATE INDEX IF NOT EXISTS ix_vr_fund_plans_category_id ON vr.fund_plans (category_id);
CREATE INDEX IF NOT EXISTS ix_vr_fund_plans_isin_code ON vr.fund_plans (isin_code);
CREATE INDEX IF NOT EXISTS ix_vr_fund_plans_amc_id ON vr.fund_plans (amc_id);

CREATE TABLE IF NOT EXISTS vr.funds_ratings (
	plan_id TEXT, 
	asset_class TEXT, 
	category TEXT, 
	change TEXT, 
	fund_rating TEXT, 
	previous_rating TEXT, 
	rating_date DATE, 
	return_grade TEXT, 
	risk_grade TEXT, 
	"Code" TEXT, 
	rta_code TEXT, 
	short_name TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_funds_ratings PRIMARY KEY (plan_id, rating_date)
);

CREATE TABLE IF NOT EXISTS vr.stats_variables (
	plan_id TEXT, 
	alpha NUMERIC, 
	alpha_stated NUMERIC, 
	as_on_date DATE, 
	beta NUMERIC, 
	beta_stated NUMERIC, 
	information_ratio NUMERIC, 
	mean NUMERIC, 
	rating_date DATE, 
	rsquare_stated NUMERIC, 
	rsquared NUMERIC, 
	sharpe_ratio NUMERIC, 
	sortino_ratio NUMERIC, 
	standard_deviation NUMERIC, 
	treynor NUMERIC, 
	treynor_stated NUMERIC, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_stats_variables PRIMARY KEY (plan_id, as_on_date)
);

CREATE TABLE IF NOT EXISTS vr.fund_return_latest (
	plan_id TEXT, 
	ret_10year NUMERIC, 
	ret_15year NUMERIC, 
	ret_1day NUMERIC, 
	ret_1month NUMERIC, 
	ret_1week NUMERIC, 
	ret_1year NUMERIC, 
	ret_20year NUMERIC, 
	ret_2year NUMERIC, 
	ret_3month NUMERIC, 
	ret_3year NUMERIC, 
	ret_4year NUMERIC, 
	ret_5year NUMERIC, 
	ret_6month NUMERIC, 
	ret_7year NUMERIC, 
	ret_9month NUMERIC, 
	ret_since_launch NUMERIC, 
	ret_ytd NUMERIC, 
	return_date DATE, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_fund_return_latest PRIMARY KEY (plan_id, return_date)
);

CREATE TABLE IF NOT EXISTS vr.composition (
	plan_id TEXT, 
	as_on_date DATE, 
	commodities NUMERIC, 
	debt NUMERIC, 
	equity NUMERIC, 
	hedged_equity NUMERIC, 
	others NUMERIC, 
	others_excluding_derivatives NUMERIC, 
	realestate NUMERIC, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_composition PRIMARY KEY (plan_id, as_on_date)
);

CREATE TABLE IF NOT EXISTS vr.fund_stylebox_sebi (
	plan_id TEXT, 
	date DATE, 
	large_percentage NUMERIC, 
	mid_percentage NUMERIC, 
	pb NUMERIC, 
	pe NUMERIC, 
	rank TEXT, 
	small_percentage NUMERIC, 
	style TEXT, 
	market_cap NUMERIC, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_fund_stylebox_sebi PRIMARY KEY (plan_id, date)
);

CREATE TABLE IF NOT EXISTS vr.sip_swp_stp_details (
	plan_id TEXT, 
	plan_name TEXT, 
	sip_dates TEXT, 
	sip_frequency TEXT, 
	sip_in_multiples_of NUMERIC, 
	sip_max_inv_amount NUMERIC, 
	sip_min_installments TEXT, 
	sip_min_inv_amount NUMERIC, 
	stp_dates TEXT, 
	stp_frequency TEXT, 
	stp_in_multiples_of NUMERIC, 
	stp_min_installments TEXT, 
	stp_min_inv_amount NUMERIC, 
	swp_dates TEXT, 
	swp_frequency TEXT, 
	swp_in_multiples_of NUMERIC, 
	swp_min_installments TEXT, 
	swp_min_inv_amount NUMERIC, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_sip_swp_stp_details PRIMARY KEY (plan_id)
);

CREATE TABLE IF NOT EXISTS vr.schemes_rollingreturns (
	plan_id TEXT, 
	obj_code TEXT, 
	rank_1095_days NUMERIC, 
	rank_14_days NUMERIC, 
	rank_180_days NUMERIC, 
	rank_1825_days NUMERIC, 
	rank_21_days NUMERIC, 
	rank_28_days NUMERIC, 
	rank_365_days NUMERIC, 
	rank_3650_days NUMERIC, 
	rank_7_days NUMERIC, 
	rank_730_days NUMERIC, 
	rank_90_days NUMERIC, 
	ret_1095_days NUMERIC, 
	ret_14_days NUMERIC, 
	ret_180_days NUMERIC, 
	ret_1825_days NUMERIC, 
	ret_21_days NUMERIC, 
	ret_28_days NUMERIC, 
	ret_365_days NUMERIC, 
	ret_3650_days NUMERIC, 
	ret_7_days NUMERIC, 
	ret_730_days NUMERIC, 
	ret_90_days NUMERIC, 
	return_date DATE, 
	type_code TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_schemes_rollingreturns PRIMARY KEY (plan_id, return_date)
);

CREATE TABLE IF NOT EXISTS vr.amcs (
	amc_id TEXT, 
	amc_full_name TEXT, 
	owner_type TEXT, 
	cio TEXT, 
	investors_relations_officer TEXT, 
	amc_short_name TEXT, 
	ceo TEXT, 
	management_trustee TEXT, 
	start_date TEXT, 
	website TEXT, 
	address1 TEXT, 
	address2 TEXT, 
	address3 TEXT, 
	city TEXT, 
	pin TEXT, 
	phone TEXT, 
	fax TEXT, 
	email TEXT, 
	is_excluded TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_amcs PRIMARY KEY (amc_id)
);

CREATE TABLE IF NOT EXISTS vr.colour_code (
	colour_id TEXT, 
	colour_name TEXT, 
	risk TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_colour_code PRIMARY KEY (colour_id)
);

CREATE TABLE IF NOT EXISTS vr.companies (
	company_id TEXT, 
	country_code TEXT, 
	full_name TEXT, 
	industry_code TEXT, 
	short_name TEXT, 
	entity_group_id TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_companies PRIMARY KEY (company_id)
);
CREATE INDEX IF NOT EXISTS ix_vr_companies_country_code ON vr.companies (country_code);
CREATE INDEX IF NOT EXISTS ix_vr_companies_industry_code ON vr.companies (industry_code);

CREATE TABLE IF NOT EXISTS vr.entity_companies (
	entity_id TEXT, 
	company TEXT, 
	short_name TEXT, 
	website TEXT, 
	country_code TEXT, 
	amfi_industry_code TEXT, 
	lei_number TEXT, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_entity_companies PRIMARY KEY (entity_id)
);
CREATE INDEX IF NOT EXISTS ix_vr_entity_companies_country_code ON vr.entity_companies (country_code);

CREATE TABLE IF NOT EXISTS vr.cat_avg_return_latest_share_class (
	category_id TEXT, 
	ret_1day NUMERIC, 
	ret_1month NUMERIC, 
	ret_1week NUMERIC, 
	ret_3month NUMERIC, 
	ret_6month NUMERIC, 
	ret_9month NUMERIC, 
	ret_since_launch NUMERIC, 
	ret_ytd NUMERIC, 
	return_date DATE, 
	type_id TEXT, 
	performance_share_class TEXT, 
	"ret_10Yr" NUMERIC, 
	ret_15yr NUMERIC, 
	"ret_1Yr" NUMERIC, 
	ret_20yr NUMERIC, 
	"ret_2Yr" NUMERIC, 
	"ret_3Yr" NUMERIC, 
	"ret_4Yr" NUMERIC, 
	"ret_5Yr" NUMERIC, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_cat_avg_return_latest_share_class PRIMARY KEY (category_id, return_date, performance_share_class)
);

CREATE TABLE IF NOT EXISTS vr.fund_rank_latest (
	plan_id TEXT, 
	rank_10year NUMERIC, 
	rank_15year NUMERIC, 
	rank_1day NUMERIC, 
	rank_1month NUMERIC, 
	rank_1week NUMERIC, 
	rank_1year NUMERIC, 
	rank_20year NUMERIC, 
	rank_2year NUMERIC, 
	rank_3month NUMERIC, 
	rank_3year NUMERIC, 
	rank_4year NUMERIC, 
	rank_5year NUMERIC, 
	rank_6month NUMERIC, 
	rank_9month NUMERIC, 
	rank_ytd NUMERIC, 
	return_date DATE, 
	_vr_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vr_fund_rank_latest PRIMARY KEY (plan_id, return_date)
);
