"""Regenerate ``docs/charts.md`` from ``CHART_TOOLS``.

Run from ``Prozpr_Backend/``::

    python3 scripts/regen_chart_docs.py

Writes a Markdown reference of every registered chart — name, selector
description, and JSON-schema of the typed payload. Designed to be a manual
developer step (not a pre-commit hook); commit the regenerated file alongside
any chart changes so reviewers can read the catalogue.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parent.parent  # Prozpr_Backend/
DOCS_FILE = REPO_ROOT / "docs" / "charts.md"

# Make ``app.*`` importable when run as a script.
sys.path.insert(0, str(REPO_ROOT))


def _front_matter() -> str:
    return (
        "<!-- Generated by scripts/regen_chart_docs.py — do not edit by hand. -->\n"
        "<!-- To refresh: cd Prozpr_Backend && python3 scripts/regen_chart_docs.py -->\n\n"
    )


def _section_for(name: str, tool: Any) -> str:
    schema_block = ""
    try:
        schema = tool.payload_cls.model_json_schema()
        schema_block = (
            "\n**Payload schema:**\n\n"
            f"```json\n{json.dumps(schema, indent=2)}\n```\n"
        )
    except Exception as exc:
        schema_block = f"\n**Payload schema:** _unavailable_ ({exc})\n"

    builder_path = (
        f"{tool.builder.__module__}.{tool.builder.__qualname__}"
    )
    return (
        f"## `{name}`\n\n"
        f"**Selector description (read by the LLM):**\n\n"
        f"> {tool.description}\n\n"
        f"**Builder:** `{builder_path}`\n"
        f"{schema_block}\n"
        "---\n\n"
    )


def main() -> None:
    from app.services.visualization_tools.registry import CHART_TOOLS

    body = ["# Chart Catalogue\n\n",
            _front_matter(),
            f"_{len(CHART_TOOLS)} charts registered._\n\n"]
    for name in sorted(CHART_TOOLS.keys()):
        body.append(_section_for(name, CHART_TOOLS[name]))

    DOCS_FILE.parent.mkdir(parents=True, exist_ok=True)
    DOCS_FILE.write_text("".join(body))
    print(f"wrote {DOCS_FILE.relative_to(REPO_ROOT)} ({len(CHART_TOOLS)} charts)")


if __name__ == "__main__":
    main()
